export const FETCH_TRENDING_GIFS = 'FETCH_TRENDING_GIFS';
export const FETCH_TRENDING_START = 'FETCH_TRENDING_START';
export const FETCH_TRENDING_SUCCESS = 'FETCH_TRENDING_SUCCESS';
export const FETCH_TRENDING_FAILED = 'FETCH_TRENDING_FAILED';

export const FETCH_RANDOM_GIFS = 'FETCH_RANDOM_GIFS';
export const FETCH_RANDOM_START = 'FETCH_RANDOM_START';
export const FETCH_RANDOM_SUCCESS = 'FETCH_RANDOM_SUCCESS';
export const FETCH_RANDOM_FAILED = 'FETCH_RANDOM_FAILED';

export const SEARCH_GIFS = 'SEARCH_GIFS';
export const SEARCH_START = 'SEACH_START';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';
export const SEARCH_FAILED = 'SEARCH_FAILED';

